### ISSUE TITLE
Implement "is-oracle-tx" support in Tendermint v0.34.24

### ISSUE THREAD

**Issue by ZaradarBH** [classic-terra/tendermint#1]
**Problem definition**
We need to implement the "is-oracle-tx" logic in Tendermint v0.34.24 if we want to upgrade without breaking the Oracle modules enforced priority, which would lead to validators getting slashed & jailed for missing votes.

**Feature specification**
Agree on which variant to use

**Additional context**
- [x] Implement "is-oracle-tx" variants for team to decide upon
- [x] Achieve consensus on the preferred solution

**Comment by inon-man** [comment]
https://github.com/classic-terra/cosmos-sdk/issues/1

**Comment by ZaradarBH** [comment]
I implemented an initial version based on the tendermint release/0.34.0 branch with tag 0.34.21 @ https://github.com/classic-terra/tendermint/tree/tendermint/release/v0.34.0

**Comment by ZaradarBH** [comment]
Tendermint 0.34.x branch with tag 0.34.21 @ https://github.com/classic-terra/tendermint/tree/tendermint/v0.34.x

**Comment by inon-man** [comment]
I will look into this issue from now on.

**Comment by ZaradarBH** [comment]
@faddat mentioned that we are now targeting 0.34.24. Is this now the new target for Tendermint? :)

**Comment by inon-man** [comment]
If it doesn't break, let's push patch version to the latest

**Comment by ZaradarBH** [comment]
In my experience the mempool alteration can be applied to all versions of tendermint, its just the tediousness of having to re-implement it all that time because the version keeps drifting. :) I will try to push for us to have a meeting tomorrow to agree on locking a version in for the upgrade :)

**Comment by ZaradarBH** [comment]
@inon-man and I had a chat about it and agreed we will lock in on version 0.34.24. Please keep this version locked until after the 1.0.5 release :)

**Comment by ZaradarBH** [comment]
https://github.com/classic-terra/tendermint/tree/v0.34.24
